---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

---
name: dummy

releases:
- name: dummy
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- azs:
  - lon02
  name: dummy
  instances: 1
  vm_type: coreNode
  stemcell: ubuntu
  networks:
  - { name: public, default: [dns, gateway] }
  - { name: private, default: [addressable] }
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
